yarnPath: .yarn/releases/yarn-4.3.1.cjs
enableGlobalCache: false
supportedArchitectures:
  os:
    - linux
    - darwin
    - win32
  cpu:
    - x64
    - arm64

nodeLinker: pnp

packageExtensions:
  "@fastify/cookie@*":
    dependencies:
      fastify: "4.28.1"
