enableGlobalCache: false

nodeLinker: pnp

packageExtensions:
  "@fastify/cookie@*":
    dependencies:
      fastify: 4.28.1

supportedArchitectures:
  cpu:
    - x64
    - arm64
  os:
    - linux
    - darwin
    - win32

yarnPath: .yarn/releases/yarn-4.5.1.cjs
